export const STUDENT_REPOSITORY = 'STUDENT_REPOSITORY';
export const ENROLLMENT_REPOSITORY = 'ENROLLMENT_REPOSITORY';
export const EXCHANGE_RATE_SERVICE = 'EXCHANGE_RATE_SERVICE';
export const UNIT_OF_WORK = 'UNIT_OF_WORK'; 